### ISSUE TITLE
Allow specifying mass fraction for composition (needs Cerberus 1.0 release)

### ISSUE THREAD

**Issue by kyleniemeyer** [Niemeyer-Research-Group/PyKED#2]
Currently only `mole-fraction` can be specified for the mixture `composition`. Using the new [`excludes` rule](http://docs.python-cerberus.org/en/latest/validation-rules.html#excludes) in [Cerberus 1.0](http://docs.python-cerberus.org/en/latest/changelog.html), we can allow the ChemKED file to specify one or the other:

```
composition: &composition
  type: list
  schema:
    type: dict
    schema:
      species:
        required: true
        type: string
      InChI:
        required: true
        type: string
      # Specify either mole fraction or mass fraction
      mole-fraction:
        required: true
        type: float
        min: 0.0
        max: 1.0
        excludes: mass-fraction
      mass-fraction:
        required: true
        type: float
        min: 0.0
        max: 1.0
        excludes: mole-fraction
```
