### ISSUE TITLE
Decide how to handle species with fractional elemental representations and no InChI etc.

### ISSUE THREAD

**Issue by bryanwweber** [Niemeyer-Research-Group/PyKED#8]
Some fuels don't have an InChI or similar identifier, such as global representations of practical fuels (e.g., C<sub>10.9</sub>H<sub>22.0</sub>). What should we do for the InChI for these fuels? One option is to put in an arbitrary string like `"This species doesn't have an InChI"` but that obviously won't validate if we get around to validating InChI values.

**Comment by kyleniemeyer** [comment]
Just to document our discussion, we proposed adding a top-level `species` object to the ChemKED schema, that would be used for mixture composition (and also possibly ignition delay target, I think). It would consist of something like:
```
species: &species
  type: dict
  schema:
    name:
      type: string
      required: true
    InChI:
      type: string
    molecular-structure:
      type: list
      schema:
        type: dict
        schema:
          element: 
            type: string
          num_atoms:
            type: float
```
